# Generated by Django 4.2.14 on 2024-07-26 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="reminder_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 25, 19, 22, 56, 413433, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
