# Generated by Django 4.2.14 on 2024-07-26 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_reminder_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="reminder_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 25, 19, 30, 47, 960908, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
