# Generated by Django 4.2.14 on 2024-07-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_alter_todo_reminder_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="reminder_date",
            field=models.DateTimeField(),
        ),
    ]
