# Generated by Django 4.2.14 on 2024-07-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
    ]
