# Generated by Django 4.2.14 on 2024-07-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_notification_todo_remove_reminder_count_not_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.todo'),
        ),
    ]
