# Generated by Django 4.2.14 on 2024-07-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_description_alter_reminder_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
